"""Increase unit_price precision

Revision ID: 6afaa87447e9
Revises: f6a3fb7b293b
Create Date: 2026-06-07 00:17:59.535543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afaa87447e9'
down_revision: Union[str, Sequence[str], None] = 'f6a3fb7b293b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'unit_price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
