"""Initial schema creation

Revision ID: f6a3fb7b293b
Revises: 
Create Date: 2026-06-05 17:40:56.719188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a3fb7b293b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_index(op.f('idx_items_category_id'), table_name='items')
    op.drop_index(op.f('idx_items_sku'), table_name='items')
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.drop_index(op.f('idx_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_item_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('idx_transactions_item_id'), 'transactions', ['item_id'], unique=False)
    op.create_index(op.f('idx_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.create_index(op.f('idx_items_sku'), 'items', ['sku'], unique=False)
    op.create_index(op.f('idx_items_category_id'), 'items', ['category_id'], unique=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###
